# Generated by Django 2.2.12 on 2020-04-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistants',
            fields=[
                ('pk_assistants', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('dsc_assistant', models.CharField(max_length=200, verbose_name='Description')),
                ('flag_logon', models.SmallIntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0, verbose_name='Requer Login')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Inserção')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Edição')),
            ],
            options={
                'verbose_name': 'Assistentes Virtuais',
                'verbose_name_plural': 'Assistentes Virtuais',
                'db_table': 'icity_assistants',
            },
        ),
    ]
