# Generated by Django 3.0.5 on 2020-05-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistants',
            fields=[
                ('pk_assistants', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('dsc_assistant', models.CharField(max_length=200, verbose_name='Description')),
                ('flag_logon', models.SmallIntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0, verbose_name='Requer Login')),
                ('assistant_class', models.CharField(max_length=100, verbose_name='Classe do Bot')),
                ('workspace_name', models.CharField(max_length=100, verbose_name='Workspace')),
                ('workspace_id', models.CharField(max_length=100, verbose_name='Workspace ID')),
                ('workspace_URL', models.TextField(verbose_name='Workspace URL')),
                ('workspace_Key', models.CharField(max_length=100, verbose_name='Workspace Key')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Inserção')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Edição')),
            ],
            options={
                'verbose_name': 'Assistentes Virtuais',
                'verbose_name_plural': 'Assistentes Virtuais',
                'db_table': 'icity_assistants',
            },
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('pk_publicity', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('title_media', models.CharField(max_length=50, verbose_name='Título')),
                ('dsc_media', models.TextField(verbose_name='Descrição')),
                ('file_path', models.FileField(upload_to='publicity', verbose_name='Imagens')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Inserção')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Edição')),
                ('fk_assistants', models.ManyToManyField(blank=True, db_table='icity_pub_assistants', to='core.Assistants')),
            ],
            options={
                'verbose_name': 'Publicidades',
                'verbose_name_plural': 'Publicidades',
                'db_table': 'icity_publicity',
            },
        ),
    ]
