# Generated by Django 3.0.5 on 2020-04-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicity',
            name='fk_assistants',
            field=models.ManyToManyField(blank=True, db_table='icity_pub_assistants', to='core.Assistants'),
        ),
    ]
