# Generated by Django 2.2.12 on 2020-04-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistants',
            name='workspace_Key',
            field=models.CharField(default=1, max_length=100, verbose_name='Workspace Key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistants',
            name='workspace_URL',
            field=models.TextField(default=1, verbose_name='Workspace URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistants',
            name='workspace_id',
            field=models.CharField(default=1, max_length=100, verbose_name='Workspace ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistants',
            name='workspace_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Workspace'),
            preserve_default=False,
        ),
    ]
