# Generated by Django 3.0.5 on 2020-04-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200416_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistants',
            name='assistant_class',
            field=models.CharField(default=' ', max_length=100, verbose_name='Classe do Bot'),
            preserve_default=False,
        ),
    ]
