# Generated by Django 2.2.12 on 2020-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200410_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('pk_publicity', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('dsc_media', models.CharField(max_length=100, verbose_name='Descrição')),
                ('file_path', models.FileField(upload_to='publicity', verbose_name='Imagens')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Inserção')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Edição')),
                ('fk_assistants', models.ManyToManyField(db_table='icity-pub-assistants', to='core.Assistants')),
            ],
            options={
                'verbose_name': 'Publicidades',
                'verbose_name_plural': 'Publicidades',
                'db_table': 'icity_publicity',
            },
        ),
    ]
