# Generated by Django 2.2.12 on 2020-04-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicity',
            name='title_media',
            field=models.CharField(default=' ', max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicity',
            name='dsc_media',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='fk_assistants',
            field=models.ManyToManyField(blank=True, db_table='icity-pub-assistants', null=True, to='core.Assistants'),
        ),
    ]
