# Generated by Django 2.2.12 on 2020-04-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200410_1900'),
        ('watson', '0003_auto_20200410_1920'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='watsonaccess',
            name='watson_acce_fk_assi_c0cc9a_idx',
        ),
        migrations.RemoveField(
            model_name='watsonaccess',
            name='fk_assistants',
        ),
        migrations.AddField(
            model_name='watsonaccess',
            name='fk_assistants',
            field=models.ManyToManyField(to='core.Assistants'),
        ),
        migrations.AlterField(
            model_name='watsoncomponents',
            name='pk_watson_components',
            field=models.CharField(choices=[('Watson Studio', 'Aprendizado de Máquina Embarcado'), ('Watson Machine Learning', 'Aprendizado de Máquina'), ('Compare and Comply', 'Processamento de Documentos'), ('Discovery', 'Busca Analítica de Conteúdo'), ('Knowledge Catalog', 'Busca, Cataloga e Compartilha Documentos'), ('Knowledge Studio', 'Aprendizado de Linguagem de Domínio'), ('Language Translator', 'Tradutor de Linguagens'), ('Natural Language Understanding', 'Analisador de Textos'), ('Personality Insights', 'Gerar Perfil Psicológico'), ('SpeechToText', 'Reconheciento de Fala'), ('TextToSpeech', 'Transforma Texto em Fala'), ('Visual Recognition', 'Reconhecimento de Imagens')], max_length=50, primary_key=True, serialize=False, verbose_name='Tipo Componente'),
        ),
    ]
